name: Run Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout test data
        uses: actions/checkout@v4
        with:
          repository: turntable-so/turntable-test-db
          path: turntable-test-db

      - name: Setup rye
        uses: eifinger/setup-rye@v3
        with:
          working-directory: backend # setup-rye doesn't support paths like ./backend

      - name: Load secrets from One Password
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ENCRYPTION_KEY: op://Env/internal/ENCRYPTION_KEY
          GOOGLE_APPLICATION_CREDENTIALS: op://Env/Google Cloud/service_account_json
          SNOWFLAKE_ACCOUNT: op://Env/Snowflake/account
          SNOWFLAKE_PASSWORD: op://Env/Snowflake/password
          SNOWFLAKE_USER: op://Env/Snowflake/username
          OPENAI_API_KEY: op://Env/OpenAI/key
          HATCHET_CLIENT_TOKEN: op://Env/Hatchet/token
          SSHKEY_0_PUBLIC: op://Env/GitHub/sshkey_0_public
          SSHKEY_0_PRIVATE: op://Env/GitHub/sshkey_0_private
          GIT_0_REPO_URL: op://Env/GitHub/git_0_repo_url


      - name: Start test resources
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.ci.yml
          up-flags: "--build"
          down-flags: -v

      - name: Install dependencies
        run: |
          rye config --set-bool behavior.use-uv=true
          rye sync --no-lock
          rye add dbt-postgres~=1.7.0
        working-directory: backend

      - name: Run tests
        run: |
          rye run pytest
        working-directory: backend
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          AWS_S3_ACCESS_KEY_ID: minio_admin
          AWS_S3_SECRET_ACCESS_KEY: minio_password
          AWS_STORAGE_BUCKET_NAME: artifacts
          AWS_S3_ENDPOINT_URL: http://localhost:9000
          POSTGRES_TEST_DB_HOST: localhost
          POSTGRES_TEST_DB_PORT: 6543
          TEST_METABASE_URI: http://localhost:4000
          DEV: "true"
          TMPDIR: ${{ runner.temp }}
          BACKEND_HOST: localhost
          FRONTEND_HOST: localhost
          LOCAL_DB: "true"
          LOCAL_HOST: "true"
          LOCAL_REDIS: "true"
